parallel-jobs = 1
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "apk"                                                   # 'both', 'apk' or 'module'
cli-source = "revanced/revanced-cli"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
rv-brand = "ReVanced Extended"
cli-version = "v4.0.0-dev.2"
patches-version = "v2.191.0-dev.12" # locks the patches version. default: latest available
integrations-version = "v0.118.0-dev.8"
excluded-patches = "custom-branding-name custom-branding-youtube-name custom-branding-icon-mmt custom-branding-icon-revancify-red custom-branding-icon-revancify-blue"
included-patches = "materialyou disable-landscape-mode hide-double-tap-overlay-filter enable-debug-logging"
version = "18.32.39"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
